version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: purchase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
      - postgres

  inventory-service:
    build: ./inventory-service
    depends_on:
      - rabbitmq

  payment-service:
    build: ./payment-service
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq

  audit-service:
    build: ./audit-service
    depends_on:
      - rabbitmq
