spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://postgres:5432/purchase
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health,info
